---
title: "Spline_GAM_Diabetes"
output: html_document
date: "2025-12-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Use relative path or current working directory
library(dplyr)
library(readr)
one_file <- c("Diabetes_imputed_dataset_1.csv")

Diabetes_df<-one_file %>%
  lapply(read.csv, stringsAsFactors = FALSE) %>%
  bind_rows() 
```

```{r}
library(mgcv)
library(dplyr)
library(PCAmixdata)
library(ggplot2)
library(tidyr)

cont_var<-c("Education","Income") #range from 1 to 6 and 1 to 8, respectively
cat_var<-c("NoDocbcCost","AnyHealthcare") #binary so 0 and 1

cont_df <- Diabetes_df[, cont_var]
cat_df  <- Diabetes_df[, cat_var] %>% mutate(across(everything(), as.factor)) #for PCAmix, they must be made into factors

spline_list <- vector("list", length = ncol(cont_df))

for (i in seq_len(ncol(cont_df))) { #for each continuous variables
  x<-cont_df[[i]]
  spline_basis<-smoothCon(s(x, k = 5), data = data.frame(x = x), knots = NULL)[[1]]$X #use smoothCon to make 5 spline basis for the variable being looped through
  spline_list[[i]]<-spline_basis 
}

X_spline <- do.call(cbind, spline_list) #spline lists as a matrix

col_has_var_index=logical(ncol(X_spline))
for (i in seq_len(ncol(X_spline))) {
  if (sd(as.numeric(X_spline[, i])) > 0) {
    col_has_var_index[i] <- TRUE
  } 
  else {
    col_has_var_index[i] <- FALSE
  }
}

X_spline <- X_spline[, col_has_var_index] #only include columns in the spline matrix that are not constant

spline_df <- as.data.frame(X_spline)

spline_colnames <- c()
index <- 1

#Need to name only columns that are not constant
for (i in seq_along(spline_list)){
  n_cols<-ncol(spline_list[[i]])
  end<-index + n_cols - 1
  cols_w_var<-which(col_has_var_index[index:end])
  if (length(cols_w_var) > 0){
    spline_colnames <- c(spline_colnames, paste0(cont_var[i], "_spline", cols_w_var))
  }
  index<-end + 1
}
colnames(spline_df)<-spline_colnames

#PCAmix can use both categorical and continuous variables
res<-PCAmix(X.quanti = spline_df, X.quali = cat_df, rename.level = TRUE, ndim = 5)

#SVI is the first principal component
Diabetes_df$SVI <- res$ind$coord[,1] #extracts PC1 for each observation

Diabetes_df$SVI_scaled<-(Diabetes_df$SVI-min(Diabetes_df$SVI))/(max(Diabetes_df$SVI)-min(Diabetes_df$SVI)) #scales SVI between 0 and 1

summary(Diabetes_df$SVI_scaled)
hist(Diabetes_df$SVI_scaled, main="SVI from PC1 (no interactions)", xlab="SVI (scaled)")
```
```{r}
#Pairwise comparison (education and income)
#Continuous by continuous pairwise (spline bases)
interaction_list<-list()
for (i in 1:(length(cont_var)-1)) {
  for (j in (i+1):length(cont_var)) {
    # Use spline_df directly instead of complex indexing into spline_list
    mat1 <- spline_df[, grep(paste0("^", cont_var[i], "_spline"), colnames(spline_df)), drop=FALSE]
    mat2 <- spline_df[, grep(paste0("^", cont_var[j], "_spline"), colnames(spline_df)), drop=FALSE]
    for (c1 in 1:ncol(mat1)) {
      for (c2 in 1:ncol(mat2)) {
        interaction_list[[paste0(colnames(mat1)[c1], "_x_", colnames(mat2)[c2])]] <- mat1[, c1] * mat2[, c2]
      }
    }
  }
}

X_interactions<-do.call(cbind, interaction_list)

#Combine spline main effects and interaction terms
X_quanti_full<-cbind(spline_df, as.data.frame(X_interactions))

res <- PCAmix(X.quanti = X_quanti_full, X.quali = cat_df, rename.level = TRUE, ndim = 5)

#PC1
Diabetes_df$SVI <- res$ind$coord[,1]

#Rescale
Diabetes_df$SVI_scaled <- (Diabetes_df$SVI-min(Diabetes_df$SVI))/(max(Diabetes_df$SVI)-min(Diabetes_df$SVI))

summary(Diabetes_df$SVI_scaled)
hist(Diabetes_df$SVI_scaled, main="SVI from PC1 (with education-income interaction)", xlab="SVI (scaled)")

```

```{r}
#All possible interactions
interaction_list <- list()

#Continuous by continuous pairwise (spline bases), Pairwise 1
if(length(cont_var) > 1){
  for(i in 1:(length(cont_var)-1)){
    for(j in (i+1):length(cont_var)){
      mat1 <- spline_df[, grep(paste0("^", cont_var[i], "_spline"), colnames(spline_df)), drop=FALSE]
      mat2 <- spline_df[, grep(paste0("^", cont_var[j], "_spline"), colnames(spline_df)), drop=FALSE]
      for(c1 in 1:ncol(mat1)){
        for(c2 in 1:ncol(mat2)){
          interaction_list[[paste0(colnames(mat1)[c1], "_x_", colnames(mat2)[c2])]] <- mat1[, c1] * mat2[, c2]
        }
      }
    }
  }
}

#Continuous by categorical pairwise, Pairwise 2
for(i in seq_along(cont_var)){
  mat <- spline_df[, grep(paste0("^", cont_var[i], "_spline"), colnames(spline_df)), drop=FALSE]
  for(j in seq_along(cat_var)){
    cat_numeric <- as.numeric(cat_df[[j]])
    for(c in 1:ncol(mat)){
      interaction_list[[paste0(colnames(mat)[c], "_x_", cat_var[j])]] <- mat[, c] * cat_numeric
    }
  }
}

#Categorical by categorical pairwise, Pairwise 3
if(length(cat_var) > 1){
  for(i in 1:(length(cat_var)-1)){
    for(j in (i+1):length(cat_var)){
      interaction_list[[paste0(cat_var[i], "_x_", cat_var[j])]] <- as.numeric(cat_df[[i]]) * as.numeric(cat_df[[j]])
    }
  }
}

#Continuous by continuous by categorical three-way comp 1
if(length(cont_var) > 1 & length(cat_var) >= 1){
  for(i in 1:(length(cont_var)-1)){
    for(j in (i+1):length(cont_var)){
      mat1 <- spline_df[, grep(paste0("^", cont_var[i], "_spline"), colnames(spline_df)), drop=FALSE]
      mat2 <- spline_df[, grep(paste0("^", cont_var[j], "_spline"), colnames(spline_df)), drop=FALSE]
      for(k in seq_along(cat_var)){
        cat_numeric <- as.numeric(cat_df[[k]])
        for(c1 in 1:ncol(mat1)){
          for(c2 in 1:ncol(mat2)){
            interaction_list[[paste0(colnames(mat1)[c1], "_x_", colnames(mat2)[c2], "_x_", cat_var[k])]] <- mat1[, c1] * mat2[, c2] * cat_numeric
          }
        }
      }
    }
  }
}

#Continuous by categorical by categorical three-way comp 2
if(length(cat_var) > 1){
  for(i in seq_along(cont_var)){
    mat <- spline_df[, grep(paste0("^", cont_var[i], "_spline"), colnames(spline_df)), drop=FALSE]
    for(j in 1:(length(cat_var)-1)){
      for(k in (j+1):length(cat_var)){
        cat_num1 <- as.numeric(cat_df[[j]])
        cat_num2 <- as.numeric(cat_df[[k]])
        for(c in 1:ncol(mat)){
          interaction_list[[paste0(colnames(mat)[c], "_x_", cat_var[j], "_x_", cat_var[k])]] <- mat[, c] * cat_num1 * cat_num2
        }
      }
    }
  }
}


#All variables (categorical by categorical by continuous by continuous four-way)
if(length(cont_var) == 2 & length(cat_var) == 2){
  mat1 <- spline_df[, grep(paste0("^", cont_var[1], "_spline"), colnames(spline_df)), drop=FALSE]
  mat2 <- spline_df[, grep(paste0("^", cont_var[2], "_spline"), colnames(spline_df)), drop=FALSE]
  cat_num1 <- as.numeric(cat_df[[1]])
  cat_num2 <- as.numeric(cat_df[[2]])
  for(c1 in 1:ncol(mat1)){
    for(c2 in 1:ncol(mat2)){
      interaction_list[[paste0(colnames(mat1)[c1], "_x_", colnames(mat2)[c2], "_x_", cat_var[1], "_x_", cat_var[2])]] <- mat1[, c1] * mat2[, c2] * cat_num1 * cat_num2
    }
  }
}

X_interactions <- as.data.frame(interaction_list)

#Main spline and all interactions
X_quanti_full <- cbind(spline_df, X_interactions)

res <- PCAmix(X.quanti = X_quanti_full,
              X.quali = cat_df,
              rename.level = TRUE,
              ndim = 5)

#PC1
Diabetes_df$SVI<-res$ind$coord[,1]

#Rescale
Diabetes_df$SVI_scaled<-(Diabetes_df$SVI-min(Diabetes_df$SVI))/(max(Diabetes_df$SVI)-min(Diabetes_df$SVI))

summary(Diabetes_df$SVI_scaled)
hist(Diabetes_df$SVI_scaled, main="SVI with all interactions", xlab="SVI (scaled)")

```

